In [134]:
import requests
import json
import pandas as pd
import numpy as np
from funciones import normalizar_nombre, clean_name

url = 'https://servicios.ine.es/wstempus/jsCache/ES/DATOS_TABLA/'

- Precios Hoteleros = 12156
- Viajes, pernoctaciones, duración media y gasto por tipo de destino principal = 12427

In [135]:
response = requests.get(url+'62490')

In [136]:
with open('62490.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

In [137]:
for x,i in enumerate(data):
    if i['Nombre'].split(',')[-1] == ' Total':
        print(x,' ',i['Nombre'])

0   Total Nacional, Viajero, Total
3   Total Nacional, Pernoctaciones, Total
6   01 Andalucía, Viajero, Total
9   01 Andalucía, Pernoctaciones, Total
12   02 Aragón, Viajero, Total
15   02 Aragón, Pernoctaciones, Total
18   03 Asturias, Principado de, Viajero, Total
21   03 Asturias, Principado de, Pernoctaciones, Total
24   04 Balears, Illes, Viajero, Total
27   04 Balears, Illes, Pernoctaciones, Total
30   05 Canarias, Viajero, Total
33   05 Canarias, Pernoctaciones, Total
36   06 Cantabria, Viajero, Total
39   06 Cantabria, Pernoctaciones, Total
42   07 Castilla y León, Viajero, Total
45   07 Castilla y León, Pernoctaciones, Total
48   08 Castilla - La Mancha, Viajero, Total
51   08 Castilla - La Mancha, Pernoctaciones, Total
54   09 Cataluña, Viajero, Total
57   09 Cataluña, Pernoctaciones, Total
60   10 Comunitat Valenciana, Viajero, Total
63   10 Comunitat Valenciana, Pernoctaciones, Total
66   11 Extremadura, Viajero, Total
69   11 Extremadura, Pernoctaciones, Total
72   12 Galicia, Viajero, Total
75   12 Galicia, Pernoctaciones, Total
78   13 Madrid, Comunidad de, Viajero, Total
81   13 Madrid, Comunidad de, Pernoctaciones, Total
84   14 Murcia, Región de, Viajero, Total
87   14 Murcia, Región de, Pernoctaciones, Total
90   15 Navarra, Comunidad Foral de, Viajero, Total
93   15 Navarra, Comunidad Foral de, Pernoctaciones, Total
96   16 País Vasco, Viajero, Total
99   16 País Vasco, Pernoctaciones, Total
102   17 Rioja, La, Viajero, Total
105   17 Rioja, La, Pernoctaciones, Total
108   18 Ceuta, Viajero, Total
111   18 Ceuta, Pernoctaciones, Total
114   19 Melilla, Viajero, Total
117   19 Melilla, Pernoctaciones, Total

In [138]:

clean_name('Total Nacional, Viajero, Total')

'Total Nacional'

In [139]:
df_viajeros = pd.DataFrame(columns=['city','Agno','Mes','Value'])
df_pernoctaciones = pd.DataFrame(columns=['city','Agno','Mes','Value'])

In [140]:
counter = 0
for i in data:
    if i['Nombre'].split(',')[-1] == ' Total':
        if i['Nombre'].split(',')[-2] == ' Pernoctaciones':
            for data_data in i['Data']:
                Agno = data_data['NombrePeriodo'].split('M')[0]
                Mes = data_data['NombrePeriodo'].split('M')[1]
                city = clean_name(i['Nombre'])
                df_pernoctaciones.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
                counter += 1
        elif i['Nombre'].split(',')[-2] == ' Viajero':
            for data_data in i['Data']:
                Agno = data_data['NombrePeriodo'].split('M')[0]
                Mes = data_data['NombrePeriodo'].split('M')[1]
                city = clean_name(i['Nombre'])
                df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
                counter += 1

C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_pernoctaciones.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_pernoctaciones.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_pernoctaciones.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_pernoctaciones.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]
C:\Users\FX516\AppData\Local\Temp\ipykernel_21232\770676513.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_viajeros.loc[counter] = [normalizar_nombre(city), Agno, Mes, data_data['Valor']]

In [144]:
df_viajeros

      city  Agno Mes      Value
0        0  2023  11   727579.0
1        0  2023  10  1099410.0
2        0  2023  09  1325483.0
3        0  2023  08  1831834.0
4        0  2023  07  1767765.0
...    ...   ...  ..        ...
3232    19  2017  05        NaN
3233    19  2017  04        NaN
3234    19  2017  03        NaN
3235    19  2017  02        NaN
3236    19  2017  01        NaN

[1660 rows x 4 columns]

In [ ]:
ids_names = {
    0 : 'España',
    1 : 'Andalucía',
    2 : 'Aragón',
    3 : 'Principado de Asturias',
    4 : 'Islas Baleares',
    5 : 'Islas Canarias',
    6 : 'Cantabria',
    7 : 'Castilla y León',
    8 : 'Castilla La Mancha',
    9 : 'Cataluña',
    10 : 'Comunidad Valenciana',
    11 : 'Extremadura',
    12 : 'Galicia',
    13 : 'Comunidad de Madrid',
    14 : 'Región de Murcia',
    15 : 'Comunidad Foral de Navarra',
    16 : 'País Vasco',
    17 :'La Rioja',
    18 :'Ceuta',
    19 :'Melilla',
}

In [146]:
df_pernoctaciones['city'] = df_pernoctaciones['city'].astype(np.int64)
df_pernoctaciones['Mes'] = df_pernoctaciones['Mes'].astype(np.int64)
df_pernoctaciones['Agno'] = df_pernoctaciones['Agno'].astype(np.int64)
df_pernoctaciones.to_csv('pernoctaciones.csv', index=False)